### ISSUE TITLE
¿El plazo de entrega sigue abierto?

### ISSUE THREAD

**Issue by Groctel** [esthergargal/Guia#1]
Comprueba que todos los grupos reducidos hayan acabado el plazo de esta entrega, no te vaya algún listo a copiártela e invalidártela. Te paso la issue porque he preguntado y me han dicho que aún hay grupos que siguen pudiendo entregar. Si no, ignora este mensaje.

**Comment by stardusther** [comment]
> Comprueba que todos los grupos reducidos hayan acabado el plazo de esta entrega, no te vaya algún listo a copiártela e invalidártela. Te paso la issue porque he preguntado y me han dicho que aún hay grupos que siguen pudiendo entregar. Si no, ignora este mensaje.

Ah es verdad, creo que algún grupo falta por entregar. ¡Muchas gracias, ahora mismo lo pongo privado!
